### ISSUE TITLE
BUG: Wrong PDF displaying in PDF preview (Document View)

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7335]
**Describe the Bug**
The wrong PDF (from another case) is displaying in the PDF preview on Document View . **See Jessica's comment**

**Business Impact/Reason for Severity**
If wrong document is displayed, it could cause user to create improper orders or take other improper actions on the case.

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
training demo 

**To Reproduce**
1. Go to a case 
2 Click document link from Docket Record 
3. Go to another case 
Click Document View 

https://drive.google.com/file/d/18Sq_LPDpayEQ6jpH6rMMIluqU3ta19Yx/view?usp=sharing

**Expected Behavior**
If user clicks Document View without selecting a specific document, the Petition PDF should display in the PDF preview. 

**Actual Behavior**
Wrong pdf (from another case) is displaying in PDF preview. Appears to be the last PDF that was displayed.

**Screenshots**

![Screen Shot 2020-10-07 at 2.23.37 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9304f8a3-9d9c-4f73-832d-0ea72575fa69)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
documentViewerToDisplay document was not being unset on tab change

PR - https://github.com/flexion/ef-cms/pull/6688
PR - https://github.com/flexion/ef-cms/pull/6787/files

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by JessicaMarine** [comment]
I think I may know what's causing the bug ustaxcourt/ef-cms#7335.  It looks like a document is not automatically selected when you go to the "Document View" -- I suspect this happened because I was routed here by clicking on "Document View" and not through a doc link on the docket record. I had this happen during the QC project and realized that it was still displaying the last PDF from the last case I was in until I selected a doc in the Document View.  I think this is solved by auto-selecting the top document in the Document View if you don't get there through a doc link on the Docket Record view. (I actually thought this was already addressed as a bug or I would've said something sooner)

**Comment by klohman** [comment]
The PDF looks like it is updating, but there is still wrong information being displayed. 

See screen recording - https://drive.google.com/file/d/1E_7dhsT-0jZfDEeja1v58TJMEOt7mdmq/view?usp=sharing

I went from case 102-20 viewing Standing Pretrial Order to 103-20 - the Document View on 103-20 should have the Petition selected in list and display Petition information above the PDF viewer. ![Screen Shot 2020-10-14 at 1.53.41 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3cf0a358-8ede-41f4-9bfc-b66aacddfc8d)
